name: build

on: [push]

env:
  BUILD_TYPE: RelWithDebInfo
  CFLAGS: -DALLOW_TIMER_SLACK

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        sed -e 's/-DNDEBUG//g' < CMakeCache.txt > CMakeCache.txt.new
        mv -- CMakeCache.txt.new CMakeCache.txt
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --output-on-failure

  testfreebsd:
    strategy:
      matrix:
        release: [12.3, 13.1]
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.2.0
      with:
        release: ${{ matrix.release }}
        envs: 'BUILD_TYPE'
        usesh: true
        prepare: pkg install -y cmake
        run: |
          mkdir build || exit 1
          cd build || exit 1
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE || exit 1
          sed -e 's/-DNDEBUG//g' < CMakeCache.txt > CMakeCache.txt.new || exit 1
          mv -- CMakeCache.txt.new CMakeCache.txt || exit 1
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE || exit 1
          cmake --build . --config $BUILD_TYPE || exit 1
          ctest -C $BUILD_TYPE --output-on-failure || exit 1

  testopenbsd:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@v0.0.6
      with:
        envs: 'BUILD_TYPE'
        usesh: true
        prepare: pkg_add cmake gcc%11
        run: |
          echo "pwd1: $PWD $GITHUB_WORKSPACE"
          cd || exit 1
          echo "pwd2: $PWD"
          ls -la /usr/lib/crt0.o || exit 1
          mkdir build || exit 1
          cd build || exit 1
          CC=x86_64-unknown-openbsd7.1-egcc cmake --trace-expand $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE || exit 1
          sed -e 's/-DNDEBUG//g' < CMakeCache.txt > CMakeCache.txt.new || exit 1
          mv -- CMakeCache.txt.new CMakeCache.txt || exit 1
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE || exit 1
          cmake --build . --config $BUILD_TYPE || exit 1
          ctest -C $BUILD_TYPE --output-on-failure || exit 1
